#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Command\SynchronizeDb;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new SynchronizeDb());

$application->run();